### ISSUE TITLE
Error: Cannot find module 'jest-resolve/build/default_resolver'

### ISSUE THREAD

**Issue by sreenishkrishnan** [salesforce/lwc-jest#41]
Error: Cannot find module 'jest-resolve/build/default_resolver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/XXXXX/Documents/Code/LightningWebComponents/MyLWC/node_modules/@lwc/jest-resolver/src/index.js:9:38)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

**Comment by sreenishkrishnan** [comment]
Hi All,
getting this issue when running ` npm run test:unit` command. any ideas how can this be resolved?
Cheers
Sree

**Comment by trevor-bliss** [comment]
Hi @sreenishkrishnan. Are you somehow using Jest version 24 in your project? If so, try downgrading to Jest 23.6.0.

In the Jest 24 major release they moved some files around and renamed some. This broke the underlying `@lwc/jest-resolver`. This has been fixed in the resolver code but is in a version that is not scheduled until the next major Salesforce release. To try to prevent this error we cap the version of Jest to 23 in this project's dependencies, but depending on where you run the tool you may be getting a different version of Jest.

**Comment by sreenishkrishnan** [comment]
Thanks @trevor-bliss , that fixed the issue. I downgraded to 23.0.0 on my dev dependencies.
`  "dependencies": {
    "jest": "^23.0.0"
  }`
